on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set host name
      run: envsubst '$${HOST}' < metabase.conf.template > ../sites-enabled/metabase.conf
      working-directory: ${{ github.workspace }}/nginx/conf.d/sites-available
      env:
        HOST: ${{ secrets.HOST }}
    - name: set environment variables
      run: envsubst '${DB_PASSWORD}' < .env.template > .env
      working-directory: ${{ github.workspace }}
      env:
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        remote_path: /opt/metabase/
        remote_host: ${{ secrets.HOST }}
        remote_port: 22
        remote_user: ${{ secrets.SSH_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
